version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:3000"
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      CLIENT_URL: http://localhost:5100
      PUBLIC_API_PORT: 8080

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - server